docs(readme): Update instructions for Windows
wireapp/wire-desktop pull request #5331
Opened 2021-09-22 13:45 UTC by tmspzz

2021-09-28 12:45 UTC, bennycode requested changes

2021-09-28 12:45 UTC, bennycode commented on README.md
> +In an admin PowerShell run
Using the PowerShell is unnecessary. Windows Command Prompt is all it needs.

2021-09-28 12:45 UTC, bennycode commented on README.md
> +Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted
No `ExecutionPolicy` needed with Windows cmd.

2022-06-09 13:00 UTC, mythsunwind commented
This PR seems to be abandoned and cannot be merged into dev without creating a lot of conflicts. I'm closing this. please feel free to open a new PR against dev for changes.

2022-06-09 13:00 UTC, closed without merging