feat: migrate to ts components
wireapp/wire-desktop pull request #6603
Opened 2023-04-17 10:20 UTC by przemvs

Migrated files from JS to TS.
https://wearezeta.atlassian.net/browse/SQSERVICES-1998

Also a lot of files fixed by eslint & prettier.

2023-04-24 09:54 UTC, atomrc commented on electron/renderer/src/components/Sidebar/Sidebar.tsx
> +            // @ts-ignore
why?

2023-04-24 09:56 UTC, atomrc commented on electron/renderer/src/components/WebView/Webview.tsx
> +        // @ts-ignore
What is the error here?

2023-04-24 09:57 UTC, atomrc commented on electron/renderer/src/components/WebView/Webview.tsx
> +        // eslint-disable-next-line react/no-unknown-property
All those disabling make me a little curious, why do we have those properties if they are unknown? Let's try to understand what is happening here and migrate/remove if needed

2023-04-24 09:59 UTC, atomrc commented on electron/renderer/src/index.tsx
> +  // @ts-ignore
what's the error here?

2023-04-24 10:00 UTC, atomrc commented on electron/renderer/src/reducers/accountReducer.js
> +import {generateUUID} from '../lib/util.js';
why adding `.js` at the end of the files?

2023-04-24 10:01 UTC, atomrc commented on electron/src/preload/preload-webview.ts
>      decrypt: async (encrypted: Uint8Array): Promise<string> => {
Let's try to better type `global` rather than ignoring TS here

2023-04-24 10:02 UTC, atomrc commented on electron/src/settings/config.ts
> +// }
Can we remove?

2023-04-24 10:03 UTC, atomrc requested changes
A few types could be improved and some `ignores` could be removed I believe

2023-04-24 10:17 UTC, PatrykBuniX commented on electron/renderer/src/components/LoadingSpinner/LoadingSpinner.tsx
> +  // webviewRef: WebviewTag | null;
👁️

2023-04-25 13:05 UTC, tlebon commented on .eslintrc.json
> +    "valid-jsdoc": "off"
why this one?

2023-04-25 13:06 UTC, tlebon commented on electron/renderer/src/components/AccountIcon/AccountIcon.tsx
> + * Copyright (C) 2023 Wire Swiss GmbH
this should remain 2018 i guess

2023-04-25 13:11 UTC, tlebon commented on electron/renderer/src/configureStore.js
> +import reducers from './reducers/index.js';
do we need the .js here?

2023-04-25 13:11 UTC, tlebon commented on electron/renderer/src/types/account.d.ts
> + * Copyright (C) 2023 Wire Swiss GmbH
2019

2023-04-25 13:13 UTC, atomrc commented on electron/src/settings/ConfigurationPersistence.ts
> +    delete globalThis._ConfigurationPersistence[name];
⚠️ you are mixing `global` and `globalThis` in this file, this is confusing

2023-04-25 13:13 UTC, tlebon commented on electron/src/sso/SingleSignOn.test.main.ts
> + * Copyright (C) 2023 Wire Swiss GmbH
```suggestion
 * Copyright (C) 2019 Wire Swiss GmbH
```

2023-04-25 13:14 UTC, tlebon commented on electron/renderer/src/selector/AccountSelector.js
> -import {config as CONFIG} from '../../../dist/settings/config';
why are we changing from dist to src? does this impact our bundle at all?

2023-05-08 07:19 UTC, PatrykBuniX commented on electron/renderer/src/components/WebView/Webview.tsx
> +  // TODO: Update data type after migration redux to TS
Redux is not migrated yet, right?

2023-05-08 07:20 UTC, PatrykBuniX commented on electron/renderer/src/components/WebView/Webview.tsx
> +    const onIpcMessage = async ({channel, args}: {args: any; channel: string}) => {
Can we fix this one already?

2023-05-08 07:30 UTC, PatrykBuniX approved these changes

2023-05-08 13:10 UTC, tlebon commented on electron/renderer/src/actions/index.js
> -export const resetIdentity = (id = true) => ({
this file isnt moving to ts?

2023-05-08 15:43 UTC, tlebon commented on electron/renderer/src/components/WebView/Webview.tsx
> +        /* Eslint disabled because we're missing webview types */
i guess theres no way around this right?

2023-05-08 15:43 UTC, tlebon commented on electron/renderer/src/components/WebView/Webview.tsx
> +        // @ts-ignore Type doesn't exist there, keep it to not broke functionality
is this necessary

2023-05-08 15:44 UTC, tlebon commented on electron/renderer/src/components/WebView/Webview.tsx
> +        /* Eslint disabled because we're missing webview types */
manual typing perhaps?

2023-05-08 15:48 UTC, tlebon commented on electron/renderer/src/components/context/ContextMenu.tsx
> +  const handleKeyDown = (event: KeyboardEvent) => {
these shouldnt be synthetic react events?

2023-05-08 15:50 UTC, tlebon commented on electron/renderer/src/components/context/ContextMenuItem.tsx
> +interface ContextMenuItem {
im wondering if this should extend some HTML element type

2023-05-08 15:51 UTC, tlebon commented on electron/renderer/src/lib/util.ts
> + * Copyright (C) 2019 Wire Swiss GmbH
i think this should probably stay the same copy

2023-05-08 15:54 UTC, tlebon commented on electron/renderer/src/actions/index.js
> -export const resetIdentity = (id = true) => ({
gotcha

2023-05-08 15:54 UTC, tlebon commented
can you check the linter warnings about deps arrays (or other things) to make sure they are all correct or if they should be changed or closed somehow.

2023-05-09 08:31 UTC, tlebon approved these changes
LGTM

2023-05-09 08:33 UTC, merged